### PR TITLE
retry fetching once before erroring

### PR DESCRIPTION
**Pull request by arajasek**
Motivated by folks switching from old snapnet params to new ones who currently fail on startup

### CODE REVIEW

**Review by Stebalien — CHANGES_REQUESTED** [review]
I don't think this is right. We:

1. Open in append mode.
2. Download the byte range starting at the current file size.

We should keep doing that. The _fix_ would be to delete the incorrect file first.

**Comment by arajasek** [comment]
@Stebalien But if we delete an incorrect file, then we're starting from scratch anyway?

**Comment by Stebalien** [comment]
But we don't do that, do we? f you wanted to do that, you'd have to open the file with `os.O_TRUNC`.

But I'm not sure if we _do_ want to do that. The current approach is designed to resume from where we left off in case of failures and that's pretty important on a slow internet connection. Ideally we'd have some way to detect "we've downloaded the entire file and it's still broken, delete and start over".

**Comment by arajasek** [comment]
Yeah, Idk if there's any way to distinguish between an incorrect and an incomplete file. Right now, when you have the wrong file at startup, it:

- detects that the current file is wrong
- decides it needs to fetch the correct file
- appends the correct file's contents to the wrong file
- sanity checks itself at the end, realizing it's produced some grotesque mongrel of a file
- deletes the mongrel
- fails, causing the lotus daemon to fail to startup

That seems bad to me, but any solution will likely impact the incomplete file case.

**Comment by arajasek** [comment]
(You're probably right about the `os.O_TRUNC` thing, though, idk how computers work)

**Comment by Stebalien** [comment]
> appends the correct file's contents to the wrong file

Not exactly. It appends the correct tail of the file to the presumed incomplete file. Of course, it looks like we don't actually _check_ if the gateway supports range queries which may be a problem.

> That seems bad to me, but any solution will likely impact the incomplete file case.

Can we not go from "fails, causing the lotus daemon to fail to startup" back to "try again"?

1. Notice that we have an incomplete file. Maybe consider outright deleting it if it's smaller than X (e..g, 10% of the target size).
2. Try to complete the file.
3. If we end up with something wrong, delete it and try again.

---

My _concern_ is that I expect the "resume" case to be more common than the corrupt file case.

**Review by magik6k — APPROVED** [review]

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
